//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BorrowDetail = new HashSet<BorrowDetail>();
        }
    
        public int BookId { get; set; }
        public string BarCode { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public System.DateTime PublisherDate { get; set; }
        public Nullable<int> BookCategroy { get; set; }
        public decimal UnitPrice { get; set; }
        public string BookImage { get; set; }
        public Nullable<int> BookCount { get; set; }
        public Nullable<int> Remainder { get; set; }
        public string BookPosition { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowDetail> BorrowDetail { get; set; }
    }
}
