//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<BorrowDetail> BorrowDetail { get; set; }
        public virtual DbSet<BorrowInfo> BorrowInfo { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<ReaderRoles> ReaderRoles { get; set; }
        public virtual DbSet<Readers> Readers { get; set; }
        public virtual DbSet<ReturnBook> ReturnBook { get; set; }
        public virtual DbSet<SysAdmins> SysAdmins { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
