//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Readers()
        {
            this.BorrowInfo = new HashSet<BorrowInfo>();
        }
    
        public int ReaderId { get; set; }
        public string ReadingCard { get; set; }
        public string ReaderName { get; set; }
        public string Gender { get; set; }
        public string IDCard { get; set; }
        public string ReaderAddress { get; set; }
        public string PostCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string ReaderImage { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public string ReaderPwd { get; set; }
        public Nullable<int> AdminId { get; set; }
        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowInfo> BorrowInfo { get; set; }
        public virtual ReaderRoles ReaderRoles { get; set; }
        public virtual SysAdmins SysAdmins { get; set; }
    }
}
